import os
import json

# check if feedback file exists in its expected location, if not create it
def create_or_open_text_file():
    try:
        file_path = 'uploads/feedback_data.txt'
        # Open the file in write and read mode ('w+'), creating it if it doesn't exist
        if not os.path.exists(file_path):
            with open(file_path, 'w+') as file:
                file.write("This is the FEEDBACK given by user after seeing the JSON result generated by you.\n")
                print(f"Text file created or already exists at: {file_path}")
        else:
            pass
    except Exception as e:
        raise e